apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details-dr
  namespace: default
spec:
  host: details
  subsets:
  - labels:
      version: details-v1
    name: details-v1
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
