apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage-dr
  namespace: default
spec:
  host: productpage
  subsets:
  - labels:
      version: productpage-v1
    name: productpage-v1
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
