apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ratings-dr
  namespace: default
spec:
  host: ratings
  subsets:
  - labels:
      version: ratings-v1
    name: ratings-v1
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
